config/routes.rb
Engage::Application.routes.draw do
  resources :posts


  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  match "curly" => "users#curly"
  match "topbar" => "topbars#topbar"
  match "test" => "users#test"
  match "dashboard" => "users#dashboard"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/models/curly.rb
class Curly < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/curlies_controller.rb
class CurliesController < ApplicationController
  # GET /curlies
  # GET /curlies.json
  def index
    @curlies = Curly.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @curlies }
    end
  end

  # GET /curlies/1
  # GET /curlies/1.json
  def show
    @curly = Curly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @curly }
    end
  end

  # GET /curlies/new
  # GET /curlies/new.json
  def new
    @curly = Curly.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @curly }
    end
  end

  # GET /curlies/1/edit
  def edit
    @curly = Curly.find(params[:id])
  end

  # POST /curlies
  # POST /curlies.json
  def create
    @curly = Curly.new(params[:curly])

    respond_to do |format|
      if @curly.save
        format.html { redirect_to @curly, notice: 'Curly was successfully created.' }
        format.json { render json: @curly, status: :created, location: @curly }
      else
        format.html { render action: "new" }
        format.json { render json: @curly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /curlies/1
  # PUT /curlies/1.json
  def update
    @curly = Curly.find(params[:id])

    respond_to do |format|
      if @curly.update_attributes(params[:curly])
        format.html { redirect_to @curly, notice: 'Curly was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @curly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curlies/1
  # DELETE /curlies/1.json
  def destroy
    @curly = Curly.find(params[:id])
    @curly.destroy

    respond_to do |format|
      format.html { redirect_to curlies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/curlies_helper.rb
module CurliesHelper
end

app/views/curlies/_form.html.erb
<%= simple_form_for(@curly) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/curlies/edit.html.erb
<h1>Editing curly</h1>

<%= render 'form' %>

<%= link_to 'Show', @curly %> |
<%= link_to 'Back', curlies_path %>

app/views/curlies/index.html.erb
<h1>Listing curlies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @curlies.each do |curly| %>
  <tr>
    <td><%= link_to 'Show', curly %></td>
    <td><%= link_to 'Edit', edit_curly_path(curly) %></td>
    <td><%= link_to 'Destroy', curly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Curly', new_curly_path %>

app/views/curlies/new.html.erb
<h1>New curly</h1>

<%= render 'form' %>

<%= link_to 'Back', curlies_path %>

app/views/curlies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_curly_path(@curly) %> |
<%= link_to 'Back', curlies_path %>