config/routes.rb
Engage::Application.routes.draw do
  resources :posts


  mount StripeEvent::Engine => '/stripe'
  get "content/gold"
  get "content/silver"
  get "content/platinum"
  match "curly" => "users#curly"
  match "topbar" => "topbars#topbar"
  match "test" => "users#test"
  match "dashboard" => "users#dashboard"

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users, :controllers => { :registrations => 'registrations' }
  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
  end
  resources :users
end

app/controllers/topbars_controller.rb
class TopbarsController < ApplicationController
  # GET /topbars
  # GET /topbars.json
  def index
    @topbars = Topbar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topbars }
    end
  end

  def topbar
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topbars }
    end
  end

  # GET /topbars/1
  # GET /topbars/1.json
  def show
    @topbar = Topbar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topbar }
    end
  end

  # GET /topbars/new
  # GET /topbars/new.json
  def new
    @topbar = Topbar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topbar }
    end
  end

  # GET /topbars/1/edit
  def edit
    @topbar = Topbar.find(params[:id])
  end

  # POST /topbars
  # POST /topbars.json
  def create
    @topbar = Topbar.new(params[:topbar])

    respond_to do |format|
      if @topbar.save
        format.html { redirect_to @topbar, notice: 'Topbar was successfully created.' }
        format.json { render json: @topbar, status: :created, location: @topbar }
      else
        format.html { render action: "new" }
        format.json { render json: @topbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topbars/1
  # PUT /topbars/1.json
  def update
    @topbar = Topbar.find(params[:id])

    respond_to do |format|
      if @topbar.update_attributes(params[:topbar])
        format.html { redirect_to @topbar, notice: 'Topbar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topbars/1
  # DELETE /topbars/1.json
  def destroy
    @topbar = Topbar.find(params[:id])
    @topbar.destroy

    respond_to do |format|
      format.html { redirect_to topbars_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topbars_helper.rb
module TopbarsHelper
end

app/views/topbars/_form.html.erb
<%= simple_form_for(@topbar) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :topbar_text %>
    <%= f.input :color %>
    <%= f.input :link %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topbars/edit.html.erb
<h1>Editing topbar</h1>

<%= render 'form' %>

<%= link_to 'Show', @topbar %> |
<%= link_to 'Back', topbars_path %>

app/views/topbars/index.html.erb
<h1>Listing topbars</h1>

<table>
  <tr>
    <th>Topbar text</th>
    <th>Color</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topbars.each do |topbar| %>
  <tr>
    <td><%= topbar.topbar_text %></td>
    <td><%= topbar.color %></td>
    <td><%= topbar.link %></td>
    <td><%= link_to 'Show', topbar %></td>
    <td><%= link_to 'Edit', edit_topbar_path(topbar) %></td>
    <td><%= link_to 'Destroy', topbar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topbar', new_topbar_path %>

app/views/topbars/new.html.erb
<h1>New topbar</h1>

<%= render 'form' %>

<%= link_to 'Back', topbars_path %>

app/views/topbars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Topbar text:</b>
  <%= @topbar.topbar_text %>
</p>

<p>
  <b>Color:</b>
  <%= @topbar.color %>
</p>

<p>
  <b>Link:</b>
  <%= @topbar.link %>
</p>


<%= link_to 'Edit', edit_topbar_path(@topbar) %> |
<%= link_to 'Back', topbars_path %>

app/views/topbars/topbar.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Sidebar content-->
      <div class="sidebar-nav">
        <div class="well" style="width:300px; padding: 8px 0;">
          <ul class="nav nav-list">
            <li class="nav-header">Widget Settings</li>
            <li><a href="#"><i class="icon-tasks"></i> Dashboard</a></li>
            <li><a href="#"><i class="icon-plus"></i> Create New Topbar <span class="badge badge-info"></span></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="span10">
      <!--Body content-->

      <div class="settings_container">
        <h1 style="font-size: 26px">Create a Topbar widget</h1>
        <div class="accordion" id="accordion2">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                Step #1 - Insert Link
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
              <div class="accordion-inner">
                <input type="text" name="name" class="url_input_field  span8" placeholder="ie - https://www.google.com">
              </div>
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                Step #2 - Choose Color
              </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
              <div class="accordion-inner">
                Enter an HTML color code
              </div>
              #<input type="text" class="html_color" value="">
            </div>
          </div>
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                Step #3 - Choose your text
              </a>
            </div>
            <div id="collapseThree" class="accordion-body collapse">
              <div class="accordion-inner">
                Choose your text
              </div>
              <input type="text" class="widget_text" value="">
            </div>
          </div>
        </div>
        <textarea  class="widget_code" style="display: none;width: 100%;height: 90px;cursor: text !important"></textarea>
        <input type="button" class="btn btn-large btn-success generate_widget" value="Generate Widget Code">
      </div>

    </div>
  </div>
</div>